# Generated by Django 4.2 on 2023-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='<built-in function id>',
            field=models.ImageField(default=1, upload_to='products/static/media'),
            preserve_default=False,
        ),
    ]
